const CONSTANTS = {
  GET_NEWS: 'GET_NEWS',
  GET_NEWS_SUCCEEDED: 'GET_NEWS_SUCCEEDED',
  GET_NEWS_FAILED: 'GET_NEWS_FAILED',
  SEARCH_NEWS: 'SEARCH_NEWS',
  SEARCH_NEWS_SUCCEEDED: 'SEARCH_NEWS_SUCCEEDED',
  SEARCH_NEWS_FAILED: 'SEARCH_NEWS_FAILED',
  RESET_NEWS: 'RESET_NEWS'
};

export default CONSTANTS;
